### ISSUE TITLE
Typescript problem

### ISSUE THREAD

**Issue by tonoslav** [BusinessDuck/react-select-item#10]
![image](https://user-images.githubusercontent.com/3399021/32383597-b73777d2-c0b8-11e7-8dd8-f2b4a5455aef.png)

For tag `<option>` attribute **value** you can assign only `string | number | string[]` so that not very good step to assign **object**  wasn't good, what now? 

This works good but not in your plugin
![image](https://user-images.githubusercontent.com/3399021/32383812-4f3ded9a-c0b9-11e7-92fc-c1b72778591e.png)

If you want to have it in object type than add it as another attribute of your plugin I think 

So than we won't add options as children but as parameter or maybe can you think about some workaround?

**Comment by BusinessDuck** [comment]
It will be refactored in next release, plugin will be separeated to optionComponent, SelectComponent, SearchComponent ...

**Comment by tonoslav** [comment]
@BusinessDuck Do you have any idea when? :)

**Comment by BusinessDuck** [comment]
@tonoslav Alredy in progress, you can see changes in react-16 branch, i have not enought time to complete it quickly, sorry. Will be done during a week, may be two

**Comment by BusinessDuck** [comment]
@tonoslav PR is incoming https://github.com/BusinessDuck/react-select-item/pull/11
