### ISSUE TITLE
Remove hard dependencies on React and ReactDOM

### ISSUE THREAD

**Issue by eltiare** [BusinessDuck/react-select-item#3]
Those of us who use Preact will thank you.

**Comment by BusinessDuck** [comment]
@eltiare Mean u remove react from all imports and add react polyfill to webpack compiler? Is that possible?

**Comment by BusinessDuck** [comment]
I rewriting by the TS ,
check this one https://github.com/BusinessDuck/react-select-item/blob/RSI-v3/src/components/ReactSelectItem.tsx

**Comment by eltiare** [comment]
@BusinessDuck Yes, it is possible. Preact has a preact-compat library that you can resolve using Webpack. It is used thusly: 

```
config = {
  resolve: {
    alias: { 'react': 'preact-compat',  'react-dom': 'preact-compat' }
  }
}
```

**Comment by BusinessDuck** [comment]
@eltiare Cool, i add this one to the 3 version. I'll notify you about it, release is very soon.

**Comment by BusinessDuck** [comment]
@eltiare done, check in v3
